# Generated by Django 4.2.4 on 2023-09-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRRHH', '0002_conveniocolectivo_empleado_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='actividadPrincipoal',
            new_name='actividadPrincipal',
        ),
    ]
