# Generated by Django 4.2.4 on 2023-09-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRRHH', '0003_rename_actividadprincipoal_empresa_actividadprincipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniocolectivo',
            name='categorias_cct',
        ),
    ]
